import {StyleSheet} from 'react-native';
import {ScreenHeight} from 'react-native-elements/dist/helpers';

import {windowWidth, windowHeight} from '../../../config/config';

export const styles = StyleSheet.create({
  container: {
    width: windowWidth,
    height: windowHeight,
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    backgroundColor: '#242A38',
  },
  scrollContainer: {
    // marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 50,
  },
  welcomeText: {
    color: 'white',
    fontSize: 24,
    lineHeight: 32,
    fontWeight: 'bold',
    letterSpacing: 0.5,
    marginBottom: '2%',
  },
  topHeader: {
    height: 50,
    width: windowWidth,
    paddingHorizontal: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  myScore: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  scoreImage: {
    // marginLeft: '35%',
  },
  scoreText: {
    fontSize: 30,
    color: 'white',
    paddingLeft: 10,
  },
  gameHeader: {
    height: 50,
    width: windowWidth,
    paddingHorizontal: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  imagePanel: {
    width: windowWidth,
  },
  objectImage: {
    overflow: 'hidden',
    borderRadius: 15,
    borderWidth: 5,
    borderColor: 'white',
    width: '80%',
    height: ScreenHeight / 2.5,
    marginHorizontal: '10%',
    marginTop: '3%',
  },
  playPanel: {
    position: 'absolute',
    bottom: 0,
    width: windowWidth,
    backgroundColor: '#158000',
    flexDirection: 'column',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
  },
  hintPanel: {
    width: '100%',
    paddingHorizontal: '20%',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  hintButton: {
    width: 40,
    height: 40,
    // marginHorizontal: 10,
    marginVertical: 10,
  },

  selectedCharsPanel: {
    width: windowWidth,
    backgroundColor: '#fbb542aa',
    paddingVertical: '2%',
    paddingHorizontal: '2%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: '10%',
    justifyContent: 'center',
  },
  selectingCharsPanel: {
    width: windowWidth,
    paddingVertical: '2%',
    marginBottom: '5%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: '10%',
    flex: 7,
    justifyContent: 'center',
  },
  charButton: {
    backgroundColor: '#f35622',
    width: 40,
    height: 40,
    borderRadius: 7,
    marginHorizontal: 10,
    marginVertical: 10,
    flex: 1,
  },
  charText: {
    fontSize: 25,
    textAlign: 'center',
    textAlignVertical: 'center',
    color: 'white',
    height: '100%',
  },
  footerContainer: {
    marginHorizontal: 10,
    marginVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  contestInfoDetail: {
    opacity: 0.85,
    color: 'white',
    fontSize: 18,
    marginVertical: 5,
    marginHorizontal: 10,
    fontFamily: 'OpenSans-Regular',
  },
  storyAuthor: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
    fontFamily: 'OpenSans-SemiBold',
    textAlign: 'right',
  },
  storyAuthorDesc: {
    fontSize: 14,
    opacity: 0.8,
    color: 'white',
    fontFamily: 'OpenSans-Regular',
    textAlign: 'right',
  },
  playerImage: {
    width: 60,
    height: 60,
    marginTop: 8,
    marginLeft: -10,
    marginRight: 5,
    overflow: 'hidden',
    borderRadius: 50,
    borderColor: '#ffffff',
    borderWidth: 2,
  },
  medalImage: {
    width: 30,
    height: 60,
    marginTop: 8,
  },
  hostImage: {
    width: 60,
    height: 60,
    marginLeft: 8,
    marginTop: -10,
    marginRight: -10,
  },
  contestBackImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    opacity: 0.1,
  },
  storyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  contestInfoName: {
    fontSize: 20,
    color: 'white',
    backgroundColor: '#db0dc733',
    width: '60%',
    textAlign: 'center',
    borderBottomRightRadius: 30,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor: '#db0dc7',
  },
  hostInfo: {
    marginTop: 10,
    marginRight: 10,
    flexDirection: 'row',
  },
  contestInfo: {
    paddingVertical: '1%',
    marginBottom: 20,
  },
  battleInfo: {
    borderRadius: 30,
    padding: 3,
    marginVertical: 10,
  },

  marquee: {
    marginTop: 15,
    height: 50,
    width: '100%',
    borderStyle: 'solid',
    borderTopWidth: 3,
    borderBottomWidth: 3,
    borderColor: '#00dbfe',
    backgroundColor: '#00dbfe33',
    alignItems: 'center',
  },
  cupsContainter: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: windowWidth,
    marginBottom: 20,
    // backgroundColor: 'blue',
  },
  silverCup: {width: '27%', alignItems: 'center', marginTop: '15%'},
  silverCupImage: {width: '100%', height: windowWidth * 0.27},
  silverCupUserName: {color: 'white', fontWeight: 'bold', fontSize: 18},
  silverCupUserExp: {
    color: 'white',
    fontSize: 17,
    textAlign: 'center',
  },
  goldCup: {width: '30%', alignItems: 'center'},
  goldCupImage: {width: '100%', height: windowWidth * 0.3},
  goldCupUserName: {color: 'white', fontWeight: 'bold', fontSize: 20},
  goldCupUserExp: {
    color: 'white',
    fontSize: 18,
    textAlign: 'center',
  },
  bronzeCup: {width: '25%', alignItems: 'center', marginTop: '17%'},
  bronzeCupImage: {width: '100%', height: windowWidth * 0.25},
  bronzeCupUserName: {color: 'white', fontWeight: 'bold', fontSize: 17},
  bronzeCupUserExp: {
    color: 'white',
    fontSize: 16,
    textAlign: 'center',
  },
  leaderBoardContainer: {
    width: windowWidth,
    paddingHorizontal: '2%',
    height: windowHeight / 1.5,
    // borderBottomWidth: 1,
  },
  leaderBoardHeader: {
    height: 80,
    // width: '80%',
    backgroundColor: '#ffffff66',
    paddingHorizontal: '5%',
    marginBottom: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  leaderBoardHeader1: {
    textAlignVertical: 'center',
    textAlign: 'left',
    color: 'white',
    fontSize: 20,
    width: '35%',
  },
  leaderBoardRow1: {
    textAlignVertical: 'center',
    textAlign: 'left',
    color: 'white',
    fontSize: 20,
  },
  leaderBoardHeader2: {
    textAlignVertical: 'center',
    textAlign: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: 20,
    width: '20%',
  },
  leaderBoardRow2: {
    textAlignVertical: 'center',
    textAlign: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: 25,
    width: '20%',
  },
  leaderBoardHeader3: {
    textAlignVertical: 'center',
    textAlign: 'right',
    color: 'white',
    fontSize: 20,
    width: '35%',
  },
  leaderBoardRow: {
    height: 75,
    // width: '80%',
    backgroundColor: '#ffffff33',
    paddingHorizontal: '5%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderColor: '#ffffffaa',
  },

  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    width: '70%',
    backgroundColor: 'white',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    borderRadius: 10,
    paddingBottom: 10,
  },
  modalHeader: {
    paddingVertical: 10,
    backgroundColor: '#182430',
    width: '100%',
    justifyContent: 'center',
    borderTopRightRadius: 7,
    borderTopLeftRadius: 7,
  },
  modalTitle: {
    fontSize: 25,
    color: 'white',
    textAlign: 'center',
  },
  modalBody: {
    padding: 15,
    justifyContent: 'center',
  },

  modalText: {
    textAlign: 'center',
    fontSize: 20,
  },
  warningText: {
    color: '#fc9900',
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
  },

  button: {
    borderRadius: 40,
    padding: 10,
    elevation: 2,
  },
  buttonNo: {
    backgroundColor: 'grey',
    flexDirection: 'row',
    width: '40%',
    marginRight: '5%',
    justifyContent: 'center',
  },
  buttonYes: {
    backgroundColor: '#2196F3',
    flexDirection: 'row',
    width: '40%',
    justifyContent: 'center',
  },
  buttonTextStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    textAlignVertical: 'center',
    paddingHorizontal: 5,
  },
});
