import {StyleSheet} from 'react-native';
import {ScreenWidth} from 'react-native-elements/dist/helpers';

import {windowWidth, windowHeight} from '../../config/config';

export const styles = StyleSheet.create({
  container: {
    width: windowWidth,
    height: windowHeight,
    display: 'flex',
    flexDirection: 'column',
    flexWrap: 'wrap',
    backgroundColor: '#242A38',
  },
  scrollContainer: {
    // marginHorizontal: 16,
    marginTop: 8,
    marginBottom: 50,
  },
  welcomeText: {
    color: 'white',
    fontSize: 24,
    lineHeight: 32,
    fontWeight: 'bold',
    letterSpacing: 0.5,
    marginBottom: '2%',
  },
  topHeader: {
    height: 50,
    width: windowWidth,
    paddingHorizontal: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerContainer: {
    position: 'absolute',
    bottom: 10,
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-around',
  },
  contestInfoDetail: {
    opacity: 0.85,
    color: 'white',
    fontSize: 18,
    marginVertical: 5,
    fontFamily: 'OpenSans-Regular',
  },
  storyAuthor: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
    fontFamily: 'OpenSans-SemiBold',
    textAlign: 'center',
  },
  playerUserName: {
    fontSize: windowWidth / 25,
    fontWeight: 'bold',
    color: 'white',
    fontFamily: 'OpenSans-SemiBold',
    textAlign: 'center',
  },
  storyAuthorDesc: {
    fontSize: 14,
    opacity: 0.8,
    color: 'white',
    fontFamily: 'OpenSans-Regular',
    textAlign: 'right',
  },
  playerImage: {
    width: ScreenWidth / 4,
    height: ScreenWidth / 4,
    marginTop: 10,
    borderWidth: 5,
    overflow: 'hidden',
    borderRadius: ScreenWidth / 4,
    borderColor: '#ffffff',
    borderWidth: 2,
  },
  medalImage: {
    width: 30,
    height: 60,
    marginTop: 8,
  },
  hostImage: {
    width: 60,
    height: 60,
    marginLeft: 8,
    marginTop: -10,
    marginRight: -10,
    overflow: 'hidden',
    borderRadius: 50,
    borderColor: '#ffffff',
    borderWidth: 2,
  },
  battleBackImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    opacity: 0.7,
  },
  storyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  contestInfoName: {
    fontSize: 20,
    color: 'white',
    backgroundColor: '#db0dc733',
    width: '60%',
    textAlign: 'center',
    borderBottomRightRadius: 30,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor: '#db0dc7',
  },
  hostInfo: {
    marginTop: 10,
    marginRight: 10,
    flexDirection: 'row',
  },
  battleInfo: {
    paddingVertical: '1%',
    width: '100%',
    height: windowWidth / 1.6,
  },

  marquee: {
    marginTop: 15,
    height: 50,
    width: '100%',
    borderStyle: 'solid',
    borderTopWidth: 3,
    borderBottomWidth: 3,
    borderColor: '#00dbfe',
    backgroundColor: '#00dbfe33',
    alignItems: 'center',
  },
  cupsContainter: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: windowWidth,
    marginBottom: 20,
    // backgroundColor: 'blue',
  },
  silverCup: {width: '27%', alignItems: 'center', marginTop: '15%'},
  silverCupImage: {width: '100%', height: windowWidth * 0.27},
  silverCupUserName: {color: 'white', fontWeight: 'bold', fontSize: 18},
  silverCupUserExp: {
    color: 'white',
    fontSize: 17,
    textAlign: 'center',
  },
  goldCup: {width: '30%', alignItems: 'center'},
  goldCupImage: {width: '100%', height: windowWidth * 0.3},
  goldCupUserName: {color: 'white', fontWeight: 'bold', fontSize: 20},
  goldCupUserExp: {
    color: 'white',
    fontSize: 18,
    textAlign: 'center',
  },
  bronzeCup: {width: '25%', alignItems: 'center', marginTop: '17%'},
  bronzeCupImage: {width: '100%', height: windowWidth * 0.25},
  bronzeCupUserName: {color: 'white', fontWeight: 'bold', fontSize: 17},
  bronzeCupUserExp: {
    color: 'white',
    fontSize: 16,
    textAlign: 'center',
  },
  leaderBoardHeader: {
    height: windowWidth / 5,
    width: '100%',
    backgroundColor: '#ffffff33',
    paddingHorizontal: '5%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 5,
    borderColor: 'white',
  },
  leaderBoardHeader1: {
    width: '35%',
    flexDirection: 'column',
  },
  playerInfo: {
    textAlignVertical: 'center',
    textAlign: 'center',
    color: 'white',
    fontSize: 20,
  },
  leaderBoardHeader2: {
    textAlignVertical: 'center',
    textAlign: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: 20,
    width: '30%',
  },
  leaderBoardHeader3: {
    textAlignVertical: 'center',
    textAlign: 'center',
    color: 'white',
    fontSize: 20,
    width: '35%',
    flexDirection: 'column',
  },
});
