import {StyleSheet} from 'react-native';

import {windowWidth, windowHeight} from '../../config/config';

export const styles = StyleSheet.create({
  storySliderBack: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    height: 32,
  },
  vpText: {
    color: 'white',
    fontSize: 10,
    fontFamily: 'OpenSans-SemiBold',
    marginLeft: 4,
  },
  vpUser: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  vpUserBorder: {
    width: 28,
    height: 28,
    borderRadius: 50,
    resizeMode: 'stretch',
    justifyContent: 'center',
    alignItems: 'center',
    // borderWidth:2,
    backgroundColor: '#242A38',
  },
  vpUserBorder_linear: {
    width: 32,
    height: 32,
    borderRadius: 50,
    justifyContent: 'center',
    alignItems: 'center',
  },
  vpImgBack: {
    width: 128,
    height: 174,
    justifyContent: 'flex-end',
    borderRadius: 8,
  },
  vpItem: {
    borderRadius: 8,
    marginRight: 16,
  },
  videoPlayContainer: {
    height: 174,
    marginTop: 16,
  },
  videoTitle: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  videoViewAll: {
    color: '#FF8B00',
    fontSize: 14,
    fontWeight: 'bold',
  },
  videoContainer: {
    marginTop: 24,
    width: windowWidth - 32,
    justifyContent: 'center',
  },
  footerContainer: {
    marginHorizontal: 10,
    marginVertical: 10,
    flexDirection: 'row',
    justifyContent: 'center',
  },
  contestViewInfo: {
    borderRadius: 30,
    backgroundColor: '#ff397f',
    width: 100,
    height: 40,
    borderWidth: 5,
    borderColor: '#ff397f55',
  },
  storySliderIndicator: {
    position: 'absolute',
    zIndex: 100,
    top: 24,
    right: 8,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(24, 24, 24, 0.8)',
    width: 35,
    height: 20,
  },
  storySliderIndicatorText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  contestInfoDetail: {
    opacity: 0.85,
    color: 'white',
    fontSize: 18,
    marginVertical: 5,
    marginHorizontal: 10,
    fontFamily: 'OpenSans-Regular',
  },
  storySliderBox: {
    marginTop: 16,
    width: windowWidth - 64,
    height: windowWidth - 64,
    borderRadius: 8,
  },
  storyAuthor: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
    fontFamily: 'OpenSans-SemiBold',
    textAlign: 'right',
  },
  storyAuthorDesc: {
    fontSize: 14,
    opacity: 0.8,
    color: 'white',
    fontFamily: 'OpenSans-Regular',
    textAlign: 'right',
  },
  playerImage: {
    width: 100,
    height: 100,
    marginTop: 10,
    borderWidth: 5,
  },
  hostImage: {
    width: 60,
    height: 60,
    marginLeft: 8,
    marginTop: -10,
    marginRight: -10,
  },
  contestBackImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    opacity: 0.1,
    borderRadius: 27,
  },
  battleBackImage: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    opacity: 0.4,
    borderRadius: 27,
  },
  storyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  contestInfoName: {
    fontSize: 20,
    color: 'white',
    backgroundColor: '#db0dc733',
    width: '60%',
    textAlign: 'center',
    borderTopLeftRadius: 30,
    borderBottomRightRadius: 30,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRightWidth: 3,
    borderBottomWidth: 3,
    borderColor: '#db0dc7',
  },
  hostInfo: {
    marginTop: 10,
    marginRight: 10,
    flexDirection: 'row',
  },
  storyContainer: {
    backgroundColor: '#2F3542',
    width: windowWidth - 32,
    marginTop: 16,
    padding: 16,
    shadowColor: 'black',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  contestInfo: {
    borderRadius: 30,
    padding: 3,
    marginVertical: 10,
  },
  battleInfo: {
    borderRadius: 30,
    padding: 3,
    marginVertical: 10,
  },
  scrollContainer: {
    // marginHorizontal:16,
    marginTop: 8,
    paddingBottom: 50,
    height: windowHeight - 200,
  },
  searchRightCircle: {
    width: 40,
    height: 40,
    marginLeft: 28,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchBar: {
    alignItems: 'center',
    paddingLeft: 44,
    width: windowWidth - 100,
    height: 40,
    color: '#595D68',
    borderRadius: 24,
    backgroundColor: '#2F3542',
    letterSpacing: 0.5,
    fontFamily: 'OpenSans-Regular',
  },
  searchContainer: {
    marginLeft: 16,
    marginRight: 16,
    marginTop: 24,
    width: windowWidth,
    flexDirection: 'row',
    height: 40,
  },
  tropyImage: {
    position: 'absolute',
    bottom: 3,
    width: windowWidth - 230,
    height: ((windowWidth - 230) / 546) * 708,
    // borderWidth: 3,
    borderColor: '#242A38',
    // borderRadius: 50,
  },
  contestWinner: {
    width: windowWidth - 250,
    height: 'auto',
    zIndex: 100,
    position: 'absolute',
    top: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  winner2Card: {
    flexDirection: 'row',
    width: 150,
    marginTop: 5,
  },
  winnerName: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 20,
  },
  winnerDate: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
  },
  winner2Name: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
    marginLeft: 10,
  },
  winner2Date: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 12,
    marginLeft: 10,
  },
  contestInfoText: {
    width: 150,
    height: 30,
    zIndex: 100,
    position: 'absolute',
    bottom: 25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  contestName: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 20,
  },
  contestDate: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
  },
  userContainer: {
    marginTop: 20,
    marginLeft: 4,
    // height: 450,
  },
  hostedByText: {
    color: 'white',
    marginTop: 4,
    fontSize: 12,
  },
  userItemContainer: {
    marginHorizontal: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userAvatarContainer: {
    width: 250,
    height: 'auto',
    borderRadius: 50,
    backgroundColor: '#595D68',
    resizeMode: 'stretch',
    justifyContent: 'center',
    alignItems: 'center',
  },
  userAvatarContainerWithBorder: {
    width: windowWidth - 100,
    height: 350,
    borderRadius: 50,
    backgroundColor: '#595D68',
    resizeMode: 'stretch',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    // borderColor:'rgba(240, 152, 25, 1)',
    // backgroundColor: '#242A38',
  },
  userAvatarContainerWithBorder_grey: {
    width: 56,
    height: 56,
    borderRadius: 50,
    backgroundColor: '#595D68',
    resizeMode: 'stretch',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(133, 140, 157, 1)',
    backgroundColor: '#242A38',
  },
  topRightCircle: {
    marginLeft: 4,
    width: 24,
    height: 24,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  container: {
    width: windowWidth,
    height: windowHeight,
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: '#242A38',
  },
  topRightHeader: {
    borderRadius: 24,
    flexDirection: 'row',
    alignItems: 'center',
    width: 56,
    height: 32,
    backgroundColor: '#181E2C',
  },
  logoBigName: {
    fontSize: 18,
    fontFamily: 'OpenSans-Bold',
    color: 'white',
    marginLeft: 8,
  },
  logoSmallName: {
    fontSize: 12,
    color: 'white',
    fontFamily: 'OpenSans-BoldItalic',
    marginTop: 6,
  },
  topHeader: {
    height: 50,
    width: windowWidth,
    paddingHorizontal: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 25,
  },
  logoImg: {
    width: 20,
    height: 24,
    marginLeft: 0.16 * windowWidth,
  },
  marquee: {
    marginTop: 15,
    height: 50,
    width: '100%',
    borderStyle: 'solid',
    borderTopWidth: 3,
    borderBottomWidth: 3,
    borderColor: '#00dbfe',
    backgroundColor: '#00dbfe33',
    alignItems: 'center',
  },
});
