
import { StyleSheet} from 'react-native';


import { windowWidth,windowHeight } from '../../config/config';

export const styles = StyleSheet.create({
	topTitle:{
		color:'white',
		fontSize:24,
		fontFamily:'Inter-SemiBold',
		lineHeight:32
	},
	tablabel:{
		color:'white',
		fontSize:14,
		fontFamily:'Inter-SemiBold',
		lineHeight:24
	},
	tabIndicator:{
		backgroundColor:'rgba(255, 121, 52, 1)',
		width:8,
		height:8,
		borderRadius:50,
		position:'absolute',
		bottom:8
	},
	topRightCircle:{
		marginLeft:5,
		width:30,
		height:30,
		borderRadius:50,
		alignItems:'center',
		justifyContent:'center'
	},
	topRightHeader:{
		marginRight:16,
		flexDirection:'row',
		alignItems:'center',
		// width:70,
		// height:40
	},
	topHeader:{
		height:50,
		width:windowWidth,
		paddingHorizontal:16,
		alignItems:'center',
		flexDirection:'row',
		justifyContent:'space-between',
		marginTop:25
	},
	footer:{
		width:windowWidth,
		alignItems:'center',
		justifyContent:'space-between',
		flexDirection:'row',
		backgroundColor:'rgba(36, 42, 56, 1)',
		paddingHorizontal:26,
		height:48
	},
	innerContainer:{
		flex: 1,
		justifyContent: "space-between"
	},
	container:{
		backgroundColor:'#2F3542',
		flex:1,
	},
	scrollContainer:{
		flex:1
	},
	profileBack:{
		width:windowWidth,
		height:windowWidth / 2
	},
	profileAvatarView:{
		marginHorizontal:40,
		flexDirection:'row',
		justifyContent:'space-between',
		alignItems:'center'
	},
	followView:{
		alignItems:'center'
	},
	followNumber:{
		color:'white'
	},
	followDesc:{
		color:'rgba(133, 140, 157, 1)'
	},
	profileAvatar:{
		width:120,
		height:120,
		borderWidth:2,
		borderRadius:100,
		borderColor:'white',
		marginTop:-60
	},
	userProfileName:{
		color:'white',
		marginTop:16,
		fontSize:18,
		lineHeight:28,
		fontFamily:'Inter-SemiBold'
	},
	userJob:{
		color:'#858C9D',
		fontSize:14,
		lineHeight:24,
		fontFamily:'Inter-Regular'
	},
	followButton:{
		width:128,
		height:40,
		borderRadius:24,
		alignItems:'center',
		justifyContent:'center'
	},
	messageButton:{
		width:128,
		height:40,
		borderRadius:24,
		alignItems:'center',
		justifyContent:'center',
		borderWidth:1,
		borderColor:'white',
		marginLeft:20
	},
	mymessageButton:{
		width:178,
		height:40,
		borderRadius:24,
		alignItems:'center',
		justifyContent:'center',
		flexDirection:'row',
		borderWidth:1,
		borderColor:'white',
		marginLeft:20
	},
	buttonText:{
		color:'white',
		fontFamily:'Inter-SemiBold',
		fontSize:14,
		lineHeight:24
	},
	userAvatar:{
		width:51,
		height:51,
		borderWidth: 3,
		borderColor:'#242A38',
		borderRadius:50
	},
	notiContainer_yellow:{
		borderRadius:50,
		backgroundColor:'#FFC542',
		width:16,
		height:16,
		zIndex:100,
		position:'absolute',
		bottom:0,
		right:0,
		borderWidth:3,
		borderColor:'#242A38'
	},
	notiContainer_green:{
		borderRadius:50,
		backgroundColor:'#3DD598',
		width:16,
		height:16,
		zIndex:100,
		position:'absolute',
		bottom:0,
		right:0,
		borderWidth:3,
		borderColor:'#242A38'
	},
	notiContainer_grey:{
		borderRadius:50,
		backgroundColor:'#858C9D',
		width:16,
		height:16,
		zIndex:100,
		position:'absolute',
		bottom:0,
		right:0,
		borderWidth:3,
		borderColor:'#242A38'
	},
	liveContainer:{
		borderRadius:4,
		backgroundColor:'#f44336',
		width:30,
		height:16,
		zIndex:100,
		position:'absolute',
		bottom:0,
		alignItems:'center',
		justifyContent:'center'
	},
	liveText:{
		color:'white',
		fontWeight:'bold',
		fontSize:10
	},
	userContainer:{
		marginTop:24,
		marginLeft:4,
		height:80
	},
	userName:{
		color:'white',
		marginTop:8,
		fontSize:12,
		fontFamily:'Inter-Regular'
	},
	userName_avatar:{
		color:'white',
		marginTop:4,
		fontSize:12
	},
	userItemContainer:{
		marginLeft:12,
		alignItems:'center',
		justifyContent:'center'
	},
	userAvatarContainer:{
		width:48,
		height:48,
		borderRadius:50,
		backgroundColor:'#595D68',
		resizeMode:'stretch',
		justifyContent:'center',
		alignItems:'center'
	},
	userAvatarContainerWithBorder:{
		width:56,
		height:56,
		borderRadius:50,
		backgroundColor:'#595D68',
		resizeMode:'stretch',
		justifyContent:'center',
		alignItems:'center',
		borderWidth:1,
		// borderColor:'rgba(240, 152, 25, 1)',
		backgroundColor:'#242A38'
	},
	userAvatarContainerWithBorder_grey:{
		width:56,
		height:56,
		borderRadius:50,
		backgroundColor:'#595D68',
		resizeMode:'stretch',
		justifyContent:'center',
		alignItems:'center',
		borderWidth:1,
		borderColor:'rgba(133, 140, 157, 1)',
		backgroundColor:'#242A38'
	},
	userAvatarContainer_nav:{
		height:32,
		borderRadius:50
	},
	navTitle:{
		alignItems:'center',
		flexDirection:'row'
	},
	navUserName:{
		color:'white',
		fontSize:16,
		lineHeight:24,
		fontFamily:'Inter-SemiBold',
		marginLeft:8
	},
});